[package]
name = "rust-bank"
version = "0.1.0"
edition = "2021"
authors = ["Felipe Miguel Nery Lunkes <felipenldev@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.5.0"
